apiVersion: apps/v1
kind: Deployment
metadata: 
  name :  httpd-frontend    
  labels:
    name: httpd-frontend
spec:
  template:
    metadata: 
      labels: 
         name: httpd-frontend
    spec: 
      containers:
      - image: nginx:stable-perl
        name: httpd-frontend
  replicas: 2
  selector: 
    matchLabels: 
      name: httpd-frontend
